import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:taxi_booking/model/taxi_booking_details/taxi_booking_details_model.dart';

class TaxiBookingDetailsViewModel extends Cubit<TaxiBookingDetailsModel> {
  TaxiBookingDetailsViewModel() : super(TaxiBookingDetailsModel());
  static TaxiBookingDetailsViewModel get(BuildContext context) => BlocProvider.of<TaxiBookingDetailsViewModel>(context);

  void setState (TaxiBookingDetailsModel state) {
    emit(state);
  }

  void setPickUpAddress (String address) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: address,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setDropOffAddress (String address) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: address,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setDate (DateTime date) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setTime (String time) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setPaymentMethod (String method) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: method,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setVehicleType (String type) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: type,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  String? getVehicleType () {
    return state.vehicleType;
  }

  void setFullName (String name) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: name,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setEmail (String email) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setPhoneNumber (String phone) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: phone,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setRoomNumber (String roomNumber) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setAdultsCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: count,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setChildrenCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: count,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setInfantsCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: count,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setPassengerComment (String comment) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: comment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setBigLuggagesCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: count,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setMediumLuggagesCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: count,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setSmallLuggagesCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: count,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setLuggagesComment (String comment) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: comment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setSurfboardCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: count,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setSkiCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: count,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setGolfCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: count,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setBikeCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: count,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setSpecialLuggagesComment (String comment) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: comment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setDogCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: count,
      catCount: state.catCount,
      petComment: state.petComment,
    ));
  }

  void setCatCount (int count) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: count,
      petComment: state.petComment,
    ));
  }

  void setPetComment (String comment) {
    emit(TaxiBookingDetailsModel(
      pickUpAddress: state.pickUpAddress,
      dropOffAddress: state.dropOffAddress,
      date: state.date,
      time: state.time,
      paymentMethod: state.paymentMethod,
      vehicleType: state.vehicleType,
      fullName: state.fullName,
      email: state.email,
      phoneNumber: state.phoneNumber,
      roomNumber: state.roomNumber,
      adultsCount: state.adultsCount,
      childrenCount: state.childrenCount,
      infantsCount: state.infantsCount,
      passengerComment: state.passengerComment,
      bigLuggagesCount: state.bigLuggagesCount,
      mediumLuggagesCount: state.mediumLuggagesCount,
      smallLuggagesCount: state.smallLuggagesCount,
      luggagesComment: state.luggagesComment,
      surfboardCount: state.surfboardCount,
      skiCount: state.skiCount,
      golfCount: state.golfCount,
      bikeCount: state.bikeCount,
      specialLuggagesComment: state.specialLuggagesComment,
      dogCount: state.dogCount,
      catCount: state.catCount,
      petComment: comment,
    ));
  }
}